name: Publish web

on:
  push:
    branches: 
      - main
      - develop
    paths:
      - "crates/web/**"
      - "Cargo.toml"
      - ".github/workflows/publish-web.yml"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rust-src
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Build
        run: "./ci/build.sh"

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_DESERT_06F1B7F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "crates/web"
          app_build_command: "echo 'manually built the crates/web/'"
          output_location: "./dist"
          production_branch: "main"
