name: Publish api

on:
  push:
    branches: [main]
    paths:
      - "crates/api/**"
      - ".github/workflows/publish-api.yml"

jobs:
  lint:
    uses: ./.github/workflows/linter.yaml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: crates/api/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crabtyper-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'crabtyper-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f9025da78314ad3a2ac8bc1af1e06e9 }}
        images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/crabtyper-api:${{ github.sha }}'
