name: Publish api

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/publish-api.yml"

jobs:
  publish:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: api/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crabtyper-api:latest
